/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/data-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Status */
        get: operations["data_status_api_v1_data_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Build Version */
        get: operations["build_version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiEnvelope[HealthData] */
        ApiEnvelope_HealthData_: {
            data: components["schemas"]["HealthData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiEnvelope[ReadinessData] */
        ApiEnvelope_ReadinessData_: {
            data: components["schemas"]["ReadinessData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiEnvelope[VersionData] */
        ApiEnvelope_VersionData_: {
            data: components["schemas"]["VersionData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiEnvelope[list[DataStatusData]] */
        ApiEnvelope_list_DataStatusData__: {
            /** Data */
            data: components["schemas"]["DataStatusData"][];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiMeta */
        ApiMeta: {
            /** Data Version */
            data_version?: string | null;
            pagination?: components["schemas"]["PaginationMeta"] | null;
            /** Request Id */
            request_id: string;
            /** Source Time */
            source_time?: string | null;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
        };
        /** DataStatusData */
        DataStatusData: {
            /** Detail */
            detail?: string | null;
            /** Freshness Status */
            freshness_status: string;
            /** Last Failure At */
            last_failure_at?: string | null;
            /** Last Success At */
            last_success_at?: string | null;
            /** Source */
            source: string;
            /** Watermark */
            watermark: string | null;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        /** HealthData */
        HealthData: {
            /**
             * Service
             * @default api
             * @constant
             */
            service: "api";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** PaginationMeta */
        PaginationMeta: {
            /** Limit */
            limit: number;
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** ReadinessData */
        ReadinessData: {
            /** Cache Status */
            cache_status: string;
            /** Database Status */
            database_status: string;
            /** Environment */
            environment: string;
            /** Schema Revision */
            schema_revision: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not-ready";
        };
        /** VersionData */
        VersionData: {
            /** Api Version */
            api_version: string;
            /** Build Sha */
            build_sha: string;
            /** Schema Revision */
            schema_revision: string;
            /**
             * Service
             * @default api
             * @constant
             */
            service: "api";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    data_status_api_v1_data_status_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_list_DataStatusData__"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_HealthData_"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    readiness_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_ReadinessData_"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    build_version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_VersionData_"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
