/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/data-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Data Status */
        get: operations["data_status_api_v1_data_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Games */
        get: operations["games_api_v1_games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Game */
        get: operations["game_api_v1_games__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{game_id}/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Game Weather */
        get: operations["game_weather_api_v1_games__game_id__weather_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matchups/batter-vs-pitcher": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Batter Pitcher Matchup */
        get: operations["batter_pitcher_matchup_api_v1_matchups_batter_vs_pitcher_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Players */
        get: operations["players_api_v1_players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Player Profile */
        get: operations["player_profile_api_v1_players__player_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weather */
        get: operations["weather_api_v1_weather_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Build Version */
        get: operations["build_version_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiEnvelope[BatterPitcherMatchupData] */
        ApiEnvelope_BatterPitcherMatchupData_: {
            data: components["schemas"]["BatterPitcherMatchupData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiEnvelope[GameData] */
        ApiEnvelope_GameData_: {
            data: components["schemas"]["GameData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiEnvelope[HealthData] */
        ApiEnvelope_HealthData_: {
            data: components["schemas"]["HealthData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiEnvelope[PlayerProfileData] */
        ApiEnvelope_PlayerProfileData_: {
            data: components["schemas"]["PlayerProfileData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiEnvelope[ReadinessData] */
        ApiEnvelope_ReadinessData_: {
            data: components["schemas"]["ReadinessData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiEnvelope[VersionData] */
        ApiEnvelope_VersionData_: {
            data: components["schemas"]["VersionData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiEnvelope[WeatherData] */
        ApiEnvelope_WeatherData_: {
            data: components["schemas"]["WeatherData"];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiEnvelope[list[DataStatusData]] */
        ApiEnvelope_list_DataStatusData__: {
            /** Data */
            data: components["schemas"]["DataStatusData"][];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiEnvelope[list[GameData]] */
        ApiEnvelope_list_GameData__: {
            /** Data */
            data: components["schemas"]["GameData"][];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiEnvelope[list[PlayerData]] */
        ApiEnvelope_list_PlayerData__: {
            /** Data */
            data: components["schemas"]["PlayerData"][];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiEnvelope[list[WeatherData]] */
        ApiEnvelope_list_WeatherData__: {
            /** Data */
            data: components["schemas"]["WeatherData"][];
            meta: components["schemas"]["ApiMeta"];
        };
        /** ApiMeta */
        ApiMeta: {
            /** Data Version */
            data_version?: string | null;
            pagination?: components["schemas"]["PaginationMeta"] | null;
            /** Request Id */
            request_id: string;
            /** Source Time */
            source_time?: string | null;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
        };
        /** BatterPitcherMatchupData */
        BatterPitcherMatchupData: {
            /** Ab */
            ab: number;
            /** Batter Id */
            batter_id: string;
            /** Batter Name */
            batter_name?: string | null;
            /** Batting Average */
            batting_average?: number | null;
            /** Doubles */
            doubles: number;
            /** Game Logs */
            game_logs: components["schemas"]["PlayerGameLogData"][];
            /** Games */
            games: number;
            /** Hit By Pitch */
            hit_by_pitch: number;
            /** Hits */
            hits: number;
            /** Home Runs */
            home_runs: number;
            /** Last Game Date */
            last_game_date?: string | null;
            /** On Base Percentage */
            on_base_percentage?: number | null;
            /** Pa */
            pa: number;
            /** Pitcher Id */
            pitcher_id: string;
            /** Pitcher Name */
            pitcher_name?: string | null;
            /** Rbi */
            rbi: number;
            /** Season */
            season?: number | null;
            /** Slugging Percentage */
            slugging_percentage?: number | null;
            /** Strikeouts */
            strikeouts: number;
            /** Total Bases */
            total_bases: number;
            /** Triples */
            triples: number;
            /** Walks */
            walks: number;
        };
        /** BattingSummaryData */
        BattingSummaryData: {
            /** Ab */
            ab: number;
            /** Batting Average */
            batting_average?: number | null;
            /** Doubles */
            doubles: number;
            /** Games */
            games: number;
            /** Hit By Pitch */
            hit_by_pitch: number;
            /** Hits */
            hits: number;
            /** Home Runs */
            home_runs: number;
            /** On Base Percentage */
            on_base_percentage?: number | null;
            /** Pa */
            pa: number;
            /** Rbi */
            rbi: number;
            /** Season */
            season: number;
            /** Slugging Percentage */
            slugging_percentage?: number | null;
            /** Strikeouts */
            strikeouts: number;
            /** Total Bases */
            total_bases: number;
            /** Triples */
            triples: number;
            /** Walks */
            walks: number;
        };
        /** DataStatusData */
        DataStatusData: {
            /** Detail */
            detail?: string | null;
            /** Freshness Status */
            freshness_status: string;
            /** Last Failure At */
            last_failure_at?: string | null;
            /** Last Success At */
            last_success_at?: string | null;
            /** Source */
            source: string;
            /** Watermark */
            watermark: string | null;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Message */
            message: string;
            /** Request Id */
            request_id: string;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        /** GameData */
        GameData: {
            away_probable_pitcher?: components["schemas"]["PitcherBrief"] | null;
            away_team: components["schemas"]["TeamBrief"];
            /**
             * Game Date
             * Format: date
             */
            game_date: string;
            /** Game Id */
            game_id: string;
            /** Game Time Utc */
            game_time_utc?: string | null;
            home_probable_pitcher?: components["schemas"]["PitcherBrief"] | null;
            home_team: components["schemas"]["TeamBrief"];
            /** Season */
            season: number;
            /** Source Updated At */
            source_updated_at?: string | null;
            /** Status */
            status?: string | null;
            venue?: components["schemas"]["VenueBrief"] | null;
        };
        /** HealthData */
        HealthData: {
            /**
             * Service
             * @default api
             * @constant
             */
            service: "api";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** PaginationMeta */
        PaginationMeta: {
            /** Limit */
            limit: number;
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** PitcherBrief */
        PitcherBrief: {
            /** Name */
            name?: string | null;
            /** Player Id */
            player_id: string;
        };
        /** PitchingSummaryData */
        PitchingSummaryData: {
            /** Batters Faced */
            batters_faced: number;
            /** Earned Run Average */
            earned_run_average?: number | null;
            /** Earned Runs */
            earned_runs: number;
            /** Games */
            games: number;
            /** Hit By Pitch */
            hit_by_pitch: number;
            /** Hits */
            hits: number;
            /** Home Runs */
            home_runs: number;
            /** Innings Outs */
            innings_outs: number;
            /** Pitch Count */
            pitch_count: number;
            /** Runs */
            runs: number;
            /** Season */
            season: number;
            /** Starts */
            starts: number;
            /** Strikeouts */
            strikeouts: number;
            /** Walks */
            walks: number;
            /** Whip */
            whip?: number | null;
        };
        /** PlayerData */
        PlayerData: {
            /** Active Status */
            active_status: string;
            /** Last Game Date */
            last_game_date?: string | null;
            /** Latest Season */
            latest_season?: number | null;
            /** Name */
            name?: string | null;
            /** Player Id */
            player_id: string;
            /** Player Type */
            player_type: string;
        };
        /** PlayerGameLogData */
        PlayerGameLogData: {
            /** Ab */
            ab?: number | null;
            /** Batters Faced */
            batters_faced?: number | null;
            /** Earned Runs */
            earned_runs?: number | null;
            /**
             * Game Date
             * Format: date
             */
            game_date: string;
            /** Game Id */
            game_id: string;
            /**
             * Games
             * @default 1
             */
            games: number;
            /** Group */
            group: string;
            /** Hits */
            hits?: number | null;
            /** Home Runs */
            home_runs?: number | null;
            /** Innings Outs */
            innings_outs?: number | null;
            /** Is Starter */
            is_starter?: boolean | null;
            /** Opponent */
            opponent?: string | null;
            /** Pa */
            pa?: number | null;
            /** Pitch Count */
            pitch_count?: number | null;
            /** Rbi */
            rbi?: number | null;
            /** Runs */
            runs?: number | null;
            /** Season */
            season: number;
            /** Strikeouts */
            strikeouts?: number | null;
            /** Total Bases */
            total_bases?: number | null;
            /** Walks */
            walks?: number | null;
        };
        /** PlayerProfileData */
        PlayerProfileData: {
            batting?: components["schemas"]["BattingSummaryData"] | null;
            /** Game Logs */
            game_logs: components["schemas"]["PlayerGameLogData"][];
            pitching?: components["schemas"]["PitchingSummaryData"] | null;
            player: components["schemas"]["PlayerData"];
            /** Selected Group */
            selected_group: string;
        };
        /** ReadinessData */
        ReadinessData: {
            /** Cache Status */
            cache_status: string;
            /** Database Status */
            database_status: string;
            /** Environment */
            environment: string;
            /** Schema Revision */
            schema_revision: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not-ready";
        };
        /** TeamBrief */
        TeamBrief: {
            /** Abbreviation */
            abbreviation?: string | null;
            /** Name */
            name: string;
            /** Score */
            score?: number | null;
        };
        /** VenueBrief */
        VenueBrief: {
            /** City */
            city?: string | null;
            /** Name */
            name: string;
            /** Roof Type */
            roof_type?: string | null;
        };
        /** VersionData */
        VersionData: {
            /** Api Version */
            api_version: string;
            /** Build Sha */
            build_sha: string;
            /** Schema Revision */
            schema_revision: string;
            /**
             * Service
             * @default api
             * @constant
             */
            service: "api";
        };
        /** WeatherData */
        WeatherData: {
            /** Available */
            available: boolean;
            away_team: components["schemas"]["TeamBrief"];
            /** Condition */
            condition?: string | null;
            /** Edge Label */
            edge_label?: string | null;
            /** Feels Like F */
            feels_like_f?: number | null;
            /** Forecast For */
            forecast_for?: string | null;
            /**
             * Game Date
             * Format: date
             */
            game_date: string;
            /** Game Id */
            game_id: string;
            /** Game Time Utc */
            game_time_utc?: string | null;
            /** Hitter Adjustment */
            hitter_adjustment?: number | null;
            home_team: components["schemas"]["TeamBrief"];
            /** Humidity Percent */
            humidity_percent?: number | null;
            /** Observed At */
            observed_at?: string | null;
            /** Pitcher Adjustment */
            pitcher_adjustment?: number | null;
            /** Precipitation Probability */
            precipitation_probability?: number | null;
            /** Source */
            source?: string | null;
            /** Status */
            status?: string | null;
            /** Temperature F */
            temperature_f?: number | null;
            venue?: components["schemas"]["VenueBrief"] | null;
            /** Wind Direction Degrees */
            wind_direction_degrees?: number | null;
            /** Wind Out Mph */
            wind_out_mph?: number | null;
            /** Wind Speed Mph */
            wind_speed_mph?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    data_status_api_v1_data_status_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_list_DataStatusData__"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    games_api_v1_games_get: {
        parameters: {
            query: {
                date: string;
                team?: string | null;
                status?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_list_GameData__"];
                };
            };
            /** @description The persisted data version has not changed */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    game_api_v1_games__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_GameData_"];
                };
            };
            /** @description The persisted data version has not changed */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    game_weather_api_v1_games__game_id__weather_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_WeatherData_"];
                };
            };
            /** @description The persisted data version has not changed */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    batter_pitcher_matchup_api_v1_matchups_batter_vs_pitcher_get: {
        parameters: {
            query: {
                batter_id: string;
                pitcher_id: string;
                season?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_BatterPitcherMatchupData_"];
                };
            };
            /** @description The persisted data version has not changed */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    players_api_v1_players_get: {
        parameters: {
            query?: {
                query?: string | null;
                role?: ("batter" | "pitcher" | "two-way") | null;
                season?: number | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_list_PlayerData__"];
                };
            };
            /** @description The persisted data version has not changed */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    player_profile_api_v1_players__player_id__get: {
        parameters: {
            query?: {
                season?: number | null;
                group?: "batting" | "pitching";
                limit?: number;
            };
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_PlayerProfileData_"];
                };
            };
            /** @description The persisted data version has not changed */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    weather_api_v1_weather_get: {
        parameters: {
            query: {
                date: string;
                game_id?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_list_WeatherData__"];
                };
            };
            /** @description The persisted data version has not changed */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_HealthData_"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    readiness_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_ReadinessData_"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    build_version_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiEnvelope_VersionData_"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
