[theme]
base = "light"
primaryColor = "#0f3b66"
backgroundColor = "#f3f5f7"
secondaryBackgroundColor = "#ffffff"
textColor = "#111827"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
